# Generated by Django 4.2.9 on 2024-04-04 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCADA_Interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=150)),
                ('machine_location', models.CharField(max_length=150)),
                ('machine_warehouse', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MachineLine_Readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('herz', models.FloatField()),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCADA_Interface.machineline')),
            ],
        ),
    ]
