# Generated by Django 4.2.9 on 2024-04-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCADA_Interface', '0002_machineline_machineline_readings'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineline_readings',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
