# Generated by Django 4.2.9 on 2024-04-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCADA_Interface', '0003_machineline_readings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineline',
            name='machine_ip_address',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='machineline',
            name='machine_rack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machineline',
            name='machine_slot',
            field=models.IntegerField(default=0),
        ),
    ]
