# Generated by Django 4.2.9 on 2024-04-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCADA_Interface', '0004_machineline_machine_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expanded_user_model',
            name='access',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Technician'), (3, 'Admin')]),
        ),
    ]
